### ISSUE TITLE
sqlitejdbc-v056.jar, c'est quoi ça?

### ISSUE THREAD

**Issue by caesarhao** [caesarhao/AgileDoctorDB#2]
Coucou, tout dans le titre. C'est le premier issue dans notre projet.

**Comment by sereneg** [comment]
Coucou, tout est dans le titre. C'est le premier  problème/question*
issue \* (issue:
Féminin) dans notre projet.

issue: sense: pas comme anglais.

http://www.linternaute.com/dictionnaire/fr/definition/issue/

—

Le 18 février 2016 à 10:30, Hao ZHANG notifications@github.com a écrit :

> Coucou, tout dans le titre. C'est le premier issue dans notre projet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/caesarhao/AgileDoctorDB/issues/2.

## 

Bien cordialement,

## Jing Guo

Phd student in Université de Toulouse Paul Sabatier
Laboratory IRIT
Centre Universitaire Jean-François Champollion

**Comment by caesarhao** [comment]
Si tu travailles dans une entreprise internationale, tu vas comprendre que issue est tjr issue.
